import { useState } from 'react';

export default function ExportModal({ isOpen, onClose, scanData }) {
  const [exporting, setExporting] = useState(null);

  if (!isOpen) return null;

  const exportMarkdown = () => {
    setExporting('md');
    const h = scanData?.healthScore || {};
    const m = scanData?.metrics || {};
    const findings = scanData?.securityFindings || [];
    const repoName = scanData?.repository?.fullName || 'Unknown';

    const md = `# CodeAtlas Analysis Report
**Repository:** ${repoName}
**Scan Date:** ${new Date(scanData?.createdAt).toLocaleString()}
**Scan ID:** ${scanData?.id}

---

## Health Scores
| Dimension | Score |
|---|---|
| Overall | ${h.overall ?? 'N/A'}/100 |
| Maintainability | ${h.maintainability ?? 'N/A'}/100 |
| Security | ${h.security ?? 'N/A'}/100 |
| Architecture | ${h.architecture ?? 'N/A'}/100 |
| Documentation | ${h.documentation ?? 'N/A'}/100 |

---

## Complexity Metrics
| Metric | Value |
|---|---|
| Total Lines of Code | ${m.totalLines ?? 0} |
| Files Analyzed | ${m.fileCount ?? 0} |
| Total Functions | ${m.functionCount ?? 0} |
| React Components | ${m.componentCount ?? 0} |
| Avg Function Length | ${Math.round(m.avgFunctionLength ?? 0)} lines |
| Max Nesting Depth | ${m.maxNestingDepth ?? 0} |

---

## Security Findings (${findings.length} total)
${findings.length === 0 ? '_No security findings._' : findings.map(f => `### [${f.severity?.toUpperCase()}] ${f.type}\n**File:** ${f.file}:${f.lineNumber}\n${f.description}\n${f.recommendation ? `**Fix:** ${f.recommendation}` : ''}`).join('\n\n')}

---

## Summary
${scanData?.summary || 'No summary available.'}

---
*Generated by CodeAtlas V2*`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `codeatlas-${repoName.replace('/', '-')}-${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
    setTimeout(() => setExporting(null), 500);
  };

  const exportJSON = () => {
    setExporting('json');
    const blob = new Blob([JSON.stringify(scanData, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `codeatlas-${(scanData?.repository?.fullName || 'scan').replace('/', '-')}-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(a.href);
    setTimeout(() => setExporting(null), 500);
  };

  const exportPDF = () => {
    onClose();
    setTimeout(() => window.print(), 100);
  };

  const options = [
    { id: 'md', label: 'Markdown Report', sub: 'Full analysis as .md file', icon: '📄', action: exportMarkdown },
    { id: 'json', label: 'JSON Export', sub: 'Raw analysis data as .json', icon: '{}', action: exportJSON },
    { id: 'pdf', label: 'PDF / Print', sub: 'Print or save as PDF via browser', icon: '🖨', action: exportPDF },
  ];

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(4px)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
      onClick={onClose}>
      <div className="modal-enter" style={{ background: 'rgba(8,8,18,0.98)', border: '1px solid rgba(255,255,255,0.1)', padding: '24px', minWidth: '320px', maxWidth: '420px', width: '100%' }}
        onClick={e => e.stopPropagation()}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <h2 style={{ fontFamily: 'monospace', fontSize: '12px', color: '#fff', letterSpacing: '0.15em', textTransform: 'uppercase', margin: 0 }}>Export Analysis</h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontSize: '16px' }}>×</button>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {options.map(opt => (
            <button key={opt.id} onClick={opt.action} disabled={exporting === opt.id}
              style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 16px', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', cursor: 'pointer', textAlign: 'left', width: '100%', transition: 'background 0.15s' }}
              onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.07)'}
              onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.03)'}>
              <span style={{ fontSize: '18px', flexShrink: 0 }}>{opt.icon}</span>
              <div>
                <div style={{ fontFamily: 'monospace', fontSize: '11px', color: '#fff', fontWeight: 'bold', marginBottom: '2px' }}>{opt.label}</div>
                <div style={{ fontFamily: 'monospace', fontSize: '9px', color: 'rgba(255,255,255,0.4)' }}>{opt.sub}</div>
              </div>
              {exporting === opt.id && <span style={{ marginLeft: 'auto', fontFamily: 'monospace', fontSize: '9px', color: '#8b5cf6' }}>EXPORTING...</span>}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
